
// Objective-C API for talking to the following Go packages
//
//	fraud-golang-interface/platforms/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ironchipauthenticatorgolangsdk_FRAMEWORK_H__
#define __Ironchipauthenticatorgolangsdk_FRAMEWORK_H__

#include "Ironchipauthenticatorgolangsdk.objc.h"
#include "Universe.objc.h"

#endif
